
server:
  port: 8080

spring:
  application:
    name: letEmCookApi
  datasource:
    url: jdbc:postgresql://localhost:5432/developer?currentSchema=recipes
    username: developer
    password: developer
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
